source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Gb-Date_Example', :exclusive => true do
  pod 'Gb-Date', :path => '../'
end

target 'Gb-Date-Cedar-Tests', :exclusive => true do
  pod 'Gb-Date', :path => '../'
  pod 'Cedar'
  
end
